#General Project Setting
project_name: BrainCancerDetection
random_seed: 42

# Data setting
data:
    raw_data: C:\Users\Tony\PycharmProjects\BrainCancerDetection\data\raw
    split_data: C:\Users\Tony\PycharmProjects\BrainCancerDetection\data\split


# Image preprocessing
image:
    image_size: [224, 224]
    batch_size: 32
    normalize: True